export default {
  MALFORMED_JSON_REQUEST_BODY: 'MALFORMED_JSON_REQUEST_BODY',
  VALIDATOR_ERROR: 'VALIDATOR_ERROR',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SUCCESS: 'SUCCESS',
  CREATED: 'CREATED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};
